minimum_pre_commit_version: 1.21.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/losisin/helm-values-schema-json
    rev: v2.3.1
    hooks:
      - id: helm-schema
        args:
          - --config
          - helm/external-secrets/.schema.yaml
  - repo: https://github.com/giantswarm/schemalint
    rev: v2.6.1
    hooks:
      - id: schemalint-normalize
        args:
          - helm/external-secrets/values.schema.json
          - -o
          - helm/external-secrets/values.schema.json
          - --force
      - id: schemalint-verify
        args:
          - helm/external-secrets/values.schema.json
  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=helm/external-secrets
          - --sort-values-order=file
