{{- if and .Values.certController.create .Values.certController.podDisruptionBudget.enabled (not .Values.webhook.certManager.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
<<<<<<< HEAD
  name: {{ include "external-secrets.name" . }}-cert-controller-pdb
=======
  name: {{ include "external-secrets.certControllerPdbName" . | quote }}
>>>>>>> b7b474e6f8dcc48764478b9e82a6e0f3c98b4e5a
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets-cert-controller.labels" . | nindent 4 }}
spec:
  {{- if .Values.certController.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.certController.podDisruptionBudget.maxUnavailable }}
  {{- else if .Values.certController.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.certController.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "external-secrets-cert-controller.selectorLabels" . | nindent 6 }}
{{- end }}
