{{ if .Capabilities.APIVersions.Has "kyverno.io/v2beta1/PolicyException" -}}
{{ if .Capabilities.APIVersions.Has "kyverno.io/v2/PolicyException" -}}
apiVersion: kyverno.io/v2
{{- else }}
apiVersion: kyverno.io/v2beta1
{{- end }}
kind: PolicyException
metadata:
  name: {{ include "external-secrets.name" . }}
  namespace: "{{ .Values.giantswarm.policyExceptionNamespace | default .Release.Namespace }}"
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  background: true
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
    - autogen-cronjob-host-path
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
    - autogen-cronjob-run-as-non-root
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
    - autogen-cronjob-restricted-volumes
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - adding-capabilities-strict
    - autogen-require-drop-all
    - autogen-cronjob-require-drop-all
    - autogen-adding-capabilities-strict
    - autogen-cronjob-adding-capabilities-strict
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        names:
          - "external-secrets*"
        namespaces:
        - "{{ .Release.Namespace }}"
{{- end }}
