{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
<<<<<<< HEAD
  name: {{ include "external-secrets.name" . }}-pdb
=======
  name: {{ include "external-secrets.pdbName" . | quote }}
>>>>>>> 3b64bba20c06c92fc1d28d87861ca844a90f4590
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "external-secrets.selectorLabels" . | nindent 6 }}
{{- end }}
