{{- if and .Values.webhook.create .Values.webhook.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
<<<<<<< HEAD
  name: {{ include "external-secrets.name" . }}-webhook-pdb
=======
  name: {{ include "external-secrets.webhookPdbName" . | quote }}
>>>>>>> 826ae5bf136a782a7f40de472da5a792ad1c43f6
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
    external-secrets.io/component: webhook
spec:
  {{- if .Values.webhook.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.webhook.podDisruptionBudget.maxUnavailable }}
  {{- else if .Values.webhook.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.webhook.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "external-secrets-webhook.selectorLabels" . | nindent 6 }}
{{- end }}
